### PR TITLE
Little source clean

### PR DESCRIPTION
**Pull request by mauronofrio**
Removed "/>" after </project>

### CODE REVIEW

**Comment by MartinX3** [comment]
Thank you ! :)
Confirmed no "repo sync" error on my build environment.

**Comment by E3enezer** [comment]
Trying to build minimal TWRP for the first time (on MacOS), no luck.
repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0 is ok, but repo sync, after downloading everything, gives
"error.GitError: android_bootable_recovery rev-list ('^66bcd499e58bf2e1a927c54085fc65e9b95ef7cb', 'HEAD', '--'): fatal: bad object 66bcd499e58bf2e1a927c54085fc65e9b95ef7cb"

**Comment by E3enezer** [comment]
I see nothing wrong with the commit https://github.com/omnirom/android_bootable_recovery/commit/66bcd499e58bf2e1a927c54085fc65e9b95ef7cb
of android_bootable_recovery...

**Comment by MartinX3** [comment]
@E3enezer

`repo forall -vc "git reset --hard"
repo --force-sync`

if the problem still exists, try it without
` --depth=1`

If it still exists, please open a bug ticket. :)

**Pull request merged**
