### PR TITLE
README: correct manifest's link

### PR DESCRIPTION
**Pull request by DroidThug**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This is already done for this branch

**Comment by DroidThug** [comment]
Fine :smile:
But I don't see the change. The link is of your old minimal manifest repo..

**Comment by ghost** [comment]
It does need to be done for the twrp-7.1 branch, feel free :+1:

**Comment by DroidThug** [comment]
This commit deals with the 7.1 branch :sweat_smile:

**Comment by ghost** [comment]
No ? You committed it to the twrp-6.0 branch ?

**Comment by DroidThug** [comment]
No, i committed it to TWRP-7.1 branch

**Review by ghost — APPROVED** [review]
Looks good to me. :+1:

**Comment by ghost** [comment]
My bad, too many pull request as of late :D

**Comment by DroidThug** [comment]
No problem. :smile_cat:

**Pull request merged**
