### PR TITLE
remove-minimal.xml: Remove nonexistent android_external_svox

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gee-one** [comment]
Here is the commit that removed android_external_svox:

https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/commit/b08a69e66f902cf36a7bae778153b908d5f4d7ed

**Comment by jcadduono** [comment]
Maybe it was meant to be platform/external/svox?

**Comment by gee-one** [comment]
I was just pointing out the upstream change.

It was always removed from the minimal build, but now it is doubly removed because of upstream changes.  The project removal in remove-minimal.xml is now redundant since it has been removed from upstream.

If upstream adds it back, then we will have to add back the line that remove it from the minimal build again.

**Comment by ghost** [comment]
@gee-one , yes, this project was removed by upstream changes, but there is a problem during use `repo sync`

> thenightdeveloper@thenightbox ~/android/RECOVERYs/minimal-twrp $ repo sync
fatal: remove-project element specifies non-existent project: android_external_svox

And after removing this line `repo sync` working fine. So, let's just remove or comment this line for now.

**Pull request merged**
