### PR TITLE
Without this i can't build the twrp

### PR DESCRIPTION
**Pull request by mauronofrio**

### CODE REVIEW

**Comment by CaptainThrowback** [comment]
I don't need this to build TWRP. However, I have "export LC_ALL=C" in my .bashrc which I believe accomplishes the same purpose, and was originally recommended to me as the solution for the problem I think you're facing.

**Comment by mauronofrio** [comment]
I have it too for latest TWRPs, but should be better to write it also in the installation guide

**Comment by CaptainThrowback** [comment]
Any reason you're using LANG=C instead of LC_ALL=C?

**Comment by mauronofrio** [comment]
I just searched for a solution on the android 6 tree and i found LANG=C if you tell me it's the same of LC_ALL=C use it, but add it in the little guide

**Comment by MartinX3** [comment]
I use
```
export LANG=de_DE.UTF-8
export LC_ALL=C
```
to fix my compiler error on my non english system.

**Comment by CaptainThrowback** [comment]
> I use
> 
> ```
> export LANG=de_DE.UTF-8
> export LC_ALL=C
> ```
> 
> to fix my compiler error on my non english system.

Does it work without the LANG line and with only LC_ALL? Or are both required?

**Comment by mauronofrio** [comment]
On android 6 i only used LANG, i used LC_ALL=C only on android 8 and android 9

**Comment by MartinX3** [comment]
Is it still needed?
I compiled AOSP 11 without setting it today.

And this PR set's `LANG` to `C`, not `LC_ALL`.
By default my `LC_ALL` is empty, but my `LANG` contains `de_DE.utf8`.

**Comment by MartinX3** [comment]
@mauronofrio @CaptainThrowback what's the current status of this PR?

**Pull request closed without merging**
