### PR TITLE
Track native-caf from OmniROM

### PR DESCRIPTION
**Pull request by MZO9400**
Change-Id: Ic53feac7d6ed24a619c7628f6b3414bc23731534

### CODE REVIEW

**Comment by ghost** [comment]
Sorry for the delay, looks good to me.

**Comment by nathanchance** [comment]
I'm curious, why was this needed? This broke building because there are two `libdumpstate.default` modules.

```build/core/base_rules.mk:157: *** frameworks/native/cmds/dumpstate: MODULE.TARGET.STATIC_LIBRARIES.libdumpstate.default already defined by frameworks/native-caf/cmds/dumpstate.  Stop.```

**Comment by MZO9400** [comment]
Back then it didn't build when I tried for my CAF device, well it didn't build because of missing native-caf

**Comment by nathanchance** [comment]
Fair enough, I just removed it with a local manifest.

**Pull request merged**
