### PR TITLE
Update to Android 7.1.2 (Nougat MR2) Release 5

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by aboyboy** [comment]
Good

**Comment by aboyboy** [comment]
I need new

**Comment by aboyboy** [comment]
.diff to the end of URLs for Git’s plaintext views.

**Comment by aboyboy** [comment]
I need to leave a comment indicating the requested changes.

**Comment by ghost** [comment]
Sorry for the delay, looks good to me.

**Pull request merged**
