### PR TITLE
Add again BusyBox

### PR DESCRIPTION
**Pull request by mauronofrio**

### CODE REVIEW

**Comment by mauronofrio** [comment]
wait to merge this

**Comment by MartinX3** [comment]
Oh, why is it needed?
I thought we switched to toybox and busybox became deprecated?

**Comment by CaptainThrowback** [comment]
We're moving away from busybox with the 9.0 tree and using toybox and associated BSD tools instead. Busybox isn't being actively updated or maintained for building purposes.

**Comment by mauronofrio** [comment]
Ok, not a problem

**Pull request closed without merging**
