### PR TITLE
manifest: Stop tracking more apps

### PR DESCRIPTION
**Pull request by theimpulson**
*None of them are required to build recovery

### CODE REVIEW

**Comment by CaptainThrowback** [comment]
Can someone please confirm this before merging?

**Comment by theimpulson** [comment]
It will be helpful if someone else can test this patch as well. 
CC: @MartinX3 @mauronofrio

**Comment by MartinX3** [comment]
Sorry for the delay
I was busy

Thank you for your contribution! :)
I build it and got successful into TWRP via `fastboot boot boot.img`.
It's okay for my side.

And thx for the pinging!

**Review by MartinX3 — APPROVED** [review]

**Comment by MartinX3** [comment]
@CaptainThrowback
If you have any comments/critics?

**Comment by CaptainThrowback** [comment]
I don't build on this tree so I have no feedback. Thanks for testing.

**Comment by MartinX3** [comment]
Okay then we merge it and if someone complains we can always revert it.

**Pull request merged**
