### PR TITLE
Move to TeamWin's android_system_update_engine

### PR DESCRIPTION
**Pull request by mauronofrio**

### CODE REVIEW

**Comment by MartinX3** [comment]
What's the advantage of the team win repo?
As far as I see it got rarely updated, last time in April with an commit from early 2018.

**Comment by CaptainThrowback** [comment]
It's needed for update_engine to build and properly work with TWRP. The Omni one doesn't.

**Comment by MartinX3** [comment]
What are the caused bugs?
I'm curious if it maybe fixes maybe my "E:Error getting bootctrl module." message, which appears since 2 or 3 security patch levels and gets fixed by manually mounting the vendor partition.

**Comment by CaptainThrowback** [comment]
@mauronofrio 

@MartinX3 Maybe you should join the [Slack channel](https://join.slack.com/t/twrptesting/shared_invite/enQtNTIwMjk0MjQ0MDAwLTMwNWQ5MzY2NGZhOWNjZWIxODJhNmMyMmQ5MjQ0NWFjYjg1ZjAzZGU2Njg3NTFiNjgxZDNhYjNhNTIwNmI3YWI) so you know what's going on.

**Comment by mauronofrio** [comment]
The problems is in the key verification, normally the update_engine_sideload should read the key and accept only the rom that are using the same key, so now all different roms are using a different key so it's a big problem. To fix this in the TeamWin branch was removed the key verification.

**Comment by MartinX3** [comment]
Thank you for the info
I use mainly the omnirom repo to build TWRP to save space on my storage (since I distribute omnirom roms, too).

**Pull request merged**
