### PR TITLE
Twrp 9.0 bringup

### PR DESCRIPTION
**Pull request by MartinX3**
Trying to bring create a minimal twrp build environment for Android Omni 9.0 PIE.

I still need a bit support from you.

I can't make a pull request into a non existing branch (twrp-9.0 does not exist).
You would need to create it and I would rebase this pull request.

Also, after compiling a bootimage, I get this error
`cp: cannot stat '/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/root/init.recovery.*.rc': No such file or directory`
and there is no "twres" folder in the ramdisk.

### CODE REVIEW

**Comment by MartinX3** [comment]
Okay, a
`make -j8 bootimage`

results into a

```
internal error: panic in GenerateBuildActions for module "gen-annotated-java-files-bp" variant "linux_glibc_x86_64_PY2"
runtime error: invalid memory address or nil pointer dereference
goroutine 246096 [running]:
github.com/google/blueprint.newPanicErrorf(0x7fdca0, 0xaf89e0, 0xc4350b6720, 0x5e, 0x0, 0x0, 0x0, 0xc441a9cb60, 0x443736)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:3462 +0x82
github.com/google/blueprint.(*Context).generateModuleBuildActions.func2.1.1(0xc439fe6000, 0xc434b95520)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2255 +0x389
panic(0x7fdca0, 0xaf89e0)
	prebuilts/go/linux-x86/src/runtime/panic.go:505 +0x229
android/soong/python.registerBuildActionForParFile(0x8f9dc0, 0xc435ecc000, 0x1, 0x0, 0x0, 0x8834c0, 0x9, 0xc435ec3e80, 0x35, 0xc420586521, ...)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/builder.go:183 +0xd03
android/soong/python.(*binaryDecorator).bootstrap(0xc440d77540, 0x8f9dc0, 0xc435ecc000, 0x87e3e4, 0x3, 0x1, 0xc428699580, 0x1, 0x1, 0x882891, ...)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/binary.go:147 +0x91b
android/soong/python.(*Module).GenerateAndroidBuildActions(0xc44093c000, 0x8f9dc0, 0xc435ecc000)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/python.go:346 +0x1c6
android/soong/android.(*ModuleBase).GenerateBuildActions(0xc44093c000, 0x8f8c60, 0xc434b95520)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/android/module.go:675 +0x6c4
github.com/google/blueprint.(*Context).generateModuleBuildActions.func2.1(0xc439fe6000, 0xc434b95520)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2259 +0x80
github.com/google/blueprint.(*Context).generateModuleBuildActions.func2(0xc439fe6000, 0x0)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2260 +0x362
github.com/google/blueprint.(*Context).parallelVisit.func1.1(0xc4402aed80, 0xc439fe6000, 0xc436e2db00, 0xc436e2d560)
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:1689 +0x30
created by github.com/google/blueprint.(*Context).parallelVisit.func1
	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:1688 +0x126
```

**Comment by wzsx150** [comment]
> Okay, a
> `make -j8 bootimage`
> 
> results into a
> 
> ```
> internal error: panic in GenerateBuildActions for module "gen-annotated-java-files-bp" variant "linux_glibc_x86_64_PY2"
> runtime error: invalid memory address or nil pointer dereference
> goroutine 246096 [running]:
> github.com/google/blueprint.newPanicErrorf(0x7fdca0, 0xaf89e0, 0xc4350b6720, 0x5e, 0x0, 0x0, 0x0, 0xc441a9cb60, 0x443736)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:3462 +0x82
> github.com/google/blueprint.(*Context).generateModuleBuildActions.func2.1.1(0xc439fe6000, 0xc434b95520)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2255 +0x389
> panic(0x7fdca0, 0xaf89e0)
> 	prebuilts/go/linux-x86/src/runtime/panic.go:505 +0x229
> android/soong/python.registerBuildActionForParFile(0x8f9dc0, 0xc435ecc000, 0x1, 0x0, 0x0, 0x8834c0, 0x9, 0xc435ec3e80, 0x35, 0xc420586521, ...)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/builder.go:183 +0xd03
> android/soong/python.(*binaryDecorator).bootstrap(0xc440d77540, 0x8f9dc0, 0xc435ecc000, 0x87e3e4, 0x3, 0x1, 0xc428699580, 0x1, 0x1, 0x882891, ...)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/binary.go:147 +0x91b
> android/soong/python.(*Module).GenerateAndroidBuildActions(0xc44093c000, 0x8f9dc0, 0xc435ecc000)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/python/python.go:346 +0x1c6
> android/soong/android.(*ModuleBase).GenerateBuildActions(0xc44093c000, 0x8f8c60, 0xc434b95520)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/soong/android/module.go:675 +0x6c4
> github.com/google/blueprint.(*Context).generateModuleBuildActions.func2.1(0xc439fe6000, 0xc434b95520)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2259 +0x80
> github.com/google/blueprint.(*Context).generateModuleBuildActions.func2(0xc439fe6000, 0x0)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:2260 +0x362
> github.com/google/blueprint.(*Context).parallelVisit.func1.1(0xc4402aed80, 0xc439fe6000, 0xc436e2db00, 0xc436e2d560)
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:1689 +0x30
> created by github.com/google/blueprint.(*Context).parallelVisit.func1
> 	/media/martin/extLinux/Develop/android/platform_manifest_twrp_omni_android_9.0/build/blueprint/context.go:1688 +0x126
> ```

how to fix the build erro？

**Comment by MartinX3** [comment]
In the next free time I will grab somehow I will try to investigate which project should be removed/added to avoid this error. :)

If you are faster than me, I would like to receive a pull request into myfork, to fix this pull request for the main project, @wzsx150 :)

**Comment by wzsx150** [comment]
maybe remove 2lines in remove-minimal.xml.   @MartinX3 
`    <remove-project name="platform/external/python/cpython2" />
    <remove-project name="platform/external/python/cpython3" />`

**Comment by MartinX3** [comment]
Thank you, @wzsx150 
I will try it, after I got some free time again. :)

**Comment by MartinX3** [comment]
I am glad that @mauronofrio is helping me. :)

**Comment by MartinX3** [comment]
@wzsx150
Thank you, today I tried it again with cpython2
Now this error got fixed.
:)

I test and look if I am finish now. :)
And commit the changes at the end of course.

**Comment by MartinX3** [comment]
So, I think I finished the work.

But now I get the same error like with the full omni 9.0 sources with TWRP.

```bash
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=omni_akari
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a9
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-43-generic-x86_64-Linux-Mint-19
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ1A.181205.006
OUT_DIR=/home/developer/android/platform_manifest_twrp_omni_android_9.0/out
============================================
[1/1] /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/soo...roid/platform_manifest_twrp_omni_android_9.0/out/soong/.bootstrap/build.ninja
[38/39] glob prebuilts/ndk/stl.bp
[74/74] /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/s...veloper/android/platform_manifest_twrp_omni_android_9.0/out/soong/build.ninja
/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/build-omni_akari-cleanspec.ninja is missing, regenerating...
/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/build-omni_akari.ninja is missing, regenerating...
[3/145] including bootable/recovery/Android.mk ...
/bin/bash: Zeile 0: test: -ge: Einstelliger (unärer) Operator erwartet.
/bin/bash: Zeile 0: test: -ge: Einstelliger (unärer) Operator erwartet.
[127/145] including system/core/Android.mk ...
sed: development/sdk/plat_tools_source.prop_template kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
sed: development/sdk/plat_tools_source.prop_template kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
[137/145] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[145/145] including vendor/omni/Android.mk ...
BOARD_KERNEL_IMAGE_NAME not defined.
vendor/omni/build/tasks/kernel.mk:167: warning: ***************************************************************
vendor/omni/build/tasks/kernel.mk:168: warning: * Using prebuilt kernel binary instead of source              *
vendor/omni/build/tasks/kernel.mk:169: warning: * THIS IS DEPRECATED, AND WILL BE DISCONTINUED                *
vendor/omni/build/tasks/kernel.mk:170: warning: * Please configure your device to download the kernel         *
vendor/omni/build/tasks/kernel.mk:171: warning: * source repository to kernel/sony/akari
vendor/omni/build/tasks/kernel.mk:172: warning: * for more information                                        *
vendor/omni/build/tasks/kernel.mk:173: warning: ***************************************************************
build/make/core/base_rules.mk:412: warning: overriding commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/recovery/root/etc/mke2fs.conf'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/recovery/root/etc/mke2fs.conf'
build/make/core/base_rules.mk:412: warning: overriding commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/root/res/images/charger/battery_fail.png'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/root/res/images/charger/battery_fail.png'
build/make/core/base_rules.mk:412: warning: overriding commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/root/res/images/charger/battery_scale.png'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/root/res/images/charger/battery_scale.png'
build/make/core/Makefile:28: warning: overriding commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/system/etc/mkshrc'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/system/etc/mkshrc'
[ 99% 548/549] glob vendor/omni/overlay/common/**/*
[  2% 320/12401] target  C++: recovery <= bootable/recovery/data.cpp
FAILED: /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/data.o 
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-4691093/bin/clang++ 	-I system/vold -I system/extras -I system/core/adb -I system/core/libsparse -I external/zlib -I bootable/recovery/bootloader_message_twrp/include -I bionic -I external/boringssl/include -I external/libcxx/include -I bootable/recovery/otautil/include -I external/libselinux/include -I system/extras/ext4_utils -I bootable/recovery -I /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates -I /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/gen/EXECUTABLES/recovery_intermediates -I libnativehelper/include_jni \$(cat /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -I frameworks/av/include -isystem /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -fdebug-prefix-map=\$PWD/= -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++14   -fno-rtti -Wall -Werror -DTW_DEVICE_VERSION='\"-0\"' -DRECOVERY_API_VERSION=3 -Wno-unused-parameter -DAB_OTA_UPDATER=1 -DTW_GIT_REVISION='\"16badcea\"' -DTW_HAS_MTP -DRECOVERY_SDCARD_ON_DATA -DCUSTOM_LUN_FILE=\\\"\"/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file\"\\\" -DTW_NO_SCREEN_BLANK -DTW_BRIGHTNESS_PATH=\"/sys/class/backlight/panel0-backlight/brightness\" -DTW_MAX_BRIGHTNESS=1023 -DQCOM_RTC_FIX -DHAVE_CAPABILITIES -DTW_USE_NEW_MINADBD -DTW_DEFAULT_LANGUAGE=en -DTWRES=\\\"/twres/\\\" -DTWHTCD_PATH=\\\"/twres/htcd/\\\" -fPIE -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch   -MD -MF /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/data.d -o /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/data.o bootable/recovery/data.cpp"
bootable/recovery/data.cpp:686:38: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                sprintf(lun_file, CUSTOM_LUN_FILE, 0);
                                  ~~~~~~~~~~~~~~~  ^
1 error generated.
[  2% 322/12401] target  C++: recovery <= bootable/recovery/partitionmanager.cpp
FAILED: /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/partitionmanager.o 
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-4691093/bin/clang++ 	-I system/vold -I system/extras -I system/core/adb -I system/core/libsparse -I external/zlib -I bootable/recovery/bootloader_message_twrp/include -I bionic -I external/boringssl/include -I external/libcxx/include -I bootable/recovery/otautil/include -I external/libselinux/include -I system/extras/ext4_utils -I bootable/recovery -I /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates -I /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/gen/EXECUTABLES/recovery_intermediates -I libnativehelper/include_jni \$(cat /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -I frameworks/av/include -isystem /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -fdebug-prefix-map=\$PWD/= -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++14   -fno-rtti -Wall -Werror -DTW_DEVICE_VERSION='\"-0\"' -DRECOVERY_API_VERSION=3 -Wno-unused-parameter -DAB_OTA_UPDATER=1 -DTW_GIT_REVISION='\"16badcea\"' -DTW_HAS_MTP -DRECOVERY_SDCARD_ON_DATA -DCUSTOM_LUN_FILE=\\\"\"/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file\"\\\" -DTW_NO_SCREEN_BLANK -DTW_BRIGHTNESS_PATH=\"/sys/class/backlight/panel0-backlight/brightness\" -DTW_MAX_BRIGHTNESS=1023 -DQCOM_RTC_FIX -DHAVE_CAPABILITIES -DTW_USE_NEW_MINADBD -DTW_DEFAULT_LANGUAGE=en -DTWRES=\\\"/twres/\\\" -DTWHTCD_PATH=\\\"/twres/htcd/\\\" -fPIE -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch   -MD -MF /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/partitionmanager.d -o /home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/recovery_intermediates/partitionmanager.o bootable/recovery/partitionmanager.cpp"
bootable/recovery/partitionmanager.cpp:1766:38: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                sprintf(lun_file, CUSTOM_LUN_FILE, 1);
                                  ~~~~~~~~~~~~~~~  ^
bootable/recovery/partitionmanager.cpp:1773:38: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                sprintf(lun_file, CUSTOM_LUN_FILE, 0);
                                  ~~~~~~~~~~~~~~~  ^
bootable/recovery/partitionmanager.cpp:1791:38: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                sprintf(lun_file, CUSTOM_LUN_FILE, 0);
                                  ~~~~~~~~~~~~~~~  ^
bootable/recovery/partitionmanager.cpp:1797:39: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                        sprintf(lun_file, CUSTOM_LUN_FILE, 1);
                                          ~~~~~~~~~~~~~~~  ^
bootable/recovery/partitionmanager.cpp:1823:38: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                sprintf(lun_file, CUSTOM_LUN_FILE, index);
                                  ~~~~~~~~~~~~~~~  ^
5 errors generated.
[  2% 327/12401] target  C++: recovery <= bootable/recovery/partition.cpp
ninja: build stopped: subcommand failed.
14:41:49 ninja failed with: exit status 1

#### failed to build some targets (40 seconds) ####
```

**Comment by MartinX3** [comment]
Maybe I need to wait for
https://github.com/oshmoun/android_bootable_recovery/tree/tama
to get into the mainline TWRP code.

This error was only a warning at my site with omni 8.1.

**Comment by MartinX3** [comment]
@CaptainThrowback is this fine?

are these compiling error warnings already fixed in gerrit?

**Comment by CaptainThrowback** [comment]
I don't have any devices that require this tree, so as such, I haven't tried building it. You'd have to check Gerrit yourself for any relevant fixes. I can make you a contributor to this project if you want to officially set up the twrp-9.0 branch here. Please let me know.

**Comment by MartinX3** [comment]
@CaptainThrowback thank you, that would be nice. :)
And I hope the minimal repo will help others. :)

BTW, I have a question according to Gerrit contributions.
Are the commits immediately merged from Gerrit into GitHub after the reviewer said ok or get commits synced only after a certain time period?

**Comment by CaptainThrowback** [comment]
Gerrit patches are merged whenever someone with rights merges them. It technically has nothing to do with the reviewers at all, though their comments may contribute to whether a patch eventually gets merged or not.

**Comment by MartinX3** [comment]
Ahh, thank you and good night. :)

**Comment by CaptainThrowback** [comment]
@MartinX3 invited you as a collaborator to the repo so you should be able to push the twrp-9.0 branch whenever it's ready.

**Comment by MartinX3** [comment]
@CaptainThrowback 
Thank you, but I think I am still not allowed to create a branch and merge this pull request. :)

**Comment by CaptainThrowback** [comment]
@MartinX3 I just sent an invite a few minutes ago. You first have to accept the invitation. Per Github, you have rights to read, clone and push to the repo.

**Comment by MartinX3** [comment]
@CaptainThrowback 
Thank you, that worked. :)
I will compile it with
https://gerrit.omnirom.org/c/android_device_sony_akari/+/33170
And if everyting is fine, merge it into the main repo as twrp-9.0 branch :)

**Comment by CaptainThrowback** [comment]
@MartinX3 Just make sure you close the pull request first and don't accidentally merge into the 8.1 branch.

EDIT: I see you're all over it - great :).

**Comment by MartinX3** [comment]
@CaptainThrowback 
Thank you for your help :)

So closing before merging?
I thought it would make both at the same time.

**Comment by CaptainThrowback** [comment]
@MartinX3 you changed the base branch so it's fine now - you just have to fix the conflicts before you can merge it, of course.

**Comment by MartinX3** [comment]
Fixed a build error and now I need to search the cause of

```bash
[ 99% 951/952] glob vendor/omni/overlay/common/**/*
ninja: error: '/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/STATIC_LIBRARIES/libxz_intermediates/export_includes', needed by '/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/update_engine_sideload_intermediates/import_includes', missing and no known rule to make it
16:48:12 ninja failed with: exit status 1
```

Seems to be xz-embedded

**Comment by CaptainThrowback** [comment]
> Fixed a build error and now I need to search the cause of
> 
> ```shell
> [ 99% 951/952] glob vendor/omni/overlay/common/**/*
> ninja: error: '/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/STATIC_LIBRARIES/libxz_intermediates/export_includes', needed by '/home/developer/android/platform_manifest_twrp_omni_android_9.0/out/target/product/akari/obj/EXECUTABLES/update_engine_sideload_intermediates/import_includes', missing and no known rule to make it
> 16:48:12 ninja failed with: exit status 1
> ```
> 
> Seems to be xz-embedded

https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/blob/twrp-9.0/remove-minimal.xml#L217

**Comment by MartinX3** [comment]
Thank you, already patched, now I search libbspatch, which looks like bsdiff :)

Now I have a job the next hours
Fulltext search my omni 9.0 sources on my computer to find the right libraries for every new build try :D

Is there a faster way?

**Comment by MartinX3** [comment]
Ahhh, everything fixed now.

Now I need to cherrypick gerrit stuff, which is still not commited on omni github.
`bootable/recovery/minuitwrp/graphics_fbdev.cpp:291:24: error: comparison of integers of different signs: 'unsigned int' and 'int' [-Werror,-Wsign-compare]`

Let's search or (unsigned) :)

Edit:
Found it:
https://gerrit.omnirom.org/c/android_bootable_recovery/+/33157

It compiles now. :D
If I'm lucky I reach 100% and can merge this pull request.

**Comment by MartinX3** [comment]
Still lacks dependencies while building the kernel

I think it is better to let this minimal twrp build the kernel, too and add the stuff
Prebuild kernels will be deprecate in the future

**Comment by CaptainThrowback** [comment]
> Still lacks dependencies while building the kernel
> 
> I think it is better to let this minimal twrp build the kernel, too and add the stuff
> Prebuild kernels will be deprecate in the future

@MartinX3 I disagree. Please don't add any kernel-only dependencies.

That will make the minimal manifest a lot less minimal. I use prebuilt kernels in all of my TWRP trees, and I don't see any real evidence of them being deprecated. Once they are, we can address it. Remember that this manifest isn't for building AOSP. TWRP trees are usually best setup with minimal dependencies, and that includes using prebuilt kernels.

**Comment by MartinX3** [comment]
Of course a prebuild kernel is fine, but while building a bootimage we get a depreciation warning.

Do you know if the feature will be removed in Omni 9.0 or 10.0?

**Comment by CaptainThrowback** [comment]
> Of course a prebuild kernel is fine, but while building a bootimage we get a depreciation warning.
> 
> Do you know if the feature will be removed in Omni 9.0 or 10.0?

That warning has been there since I started building TWRP, several Android versions and build trees ago. That's an AOSP warning that never came to fruition. I wouldn't worry about it - I doubt it'll be removed any time soon. And again, it's still present now, so we will continue as it is.

**Comment by MartinX3** [comment]
That's good to hear :)

**Comment by MartinX3** [comment]
So, now I made sure, that I didn't included a project dependency for the kernel.

Now I will place a prebuild kernel at the correct path and build again

**Comment by MartinX3** [comment]
@CaptainThrowback 
qcom needs
`export TARGET_COMPILE_WITH_MSM_KERNEL=false`
if we want to use a prebuild kernel

sadly it get set
https://github.com/omnirom/android_device_sony_common/blob/android-9.0/omni.mk#L27

means that you can't just
`export TARGET_COMPILE_WITH_MSM_KERNEL=false`
before building it

Should we note/hint this somewhere?

**Comment by CaptainThrowback** [comment]
> @CaptainThrowback
> qcom needs
> `export TARGET_COMPILE_WITH_MSM_KERNEL=false`
> if we want to use a prebuild kernel
> 
> sadly it get set
> https://github.com/omnirom/android_device_sony_common/blob/android-9.0/omni.mk#L27
> 
> means that you can't just
> `export TARGET_COMPILE_WITH_MSM_KERNEL=false`
> before building it
> 
> Should we note/hint this somewhere?

You can't just unset it (or set it to false) to do a test build? I don't have any devices with Pie, unfortunately, so I can't help you with this. I don't maintain TWRP anymore, so I won't be able to help you with anything.

**Comment by MartinX3** [comment]
Thank you and good to know :)

It is a bit difficult to know who develops TWRP and who does not (anymore) :)

I will crack me something together to full test this pull request before merging. :)

Btw.
Since PIE we got A/B devices and need the update_engine for TWRP.
Means new needed dependencies. With a prebuild kernel of course. :)
Will compare the size with full omni, after I finished my work.

**Comment by MartinX3** [comment]
I need to build in "eng" mode, instead of "userdebug" to get TWRP into the ramdisk.

Do you know why?

And the build size comparison
omni_9.0 = 74.6 GB
minimal-manifest-twrp_omni_9.0 = 31.8 GB
minimal-manifest-twrp_omni_8.1 = 24.6 GB

But now it needs A/B support and more encryption support.
update_engine forced more dependencies.

**Comment by CaptainThrowback** [comment]
TWRP is always built as -eng.

And the previous trees didn't include support for building update-engine from source - that has been left to local manifests in the past.

**Comment by MartinX3** [comment]
Good to know and I am happy that this 9.0 stuff still only needs the half size of the full Omni 9.0.

Seems that A/B is a thing now, if it got into the tree.
Most of the new devices use it.

**Comment by GuaiYiHu** [comment]
How to fix this error
ninja: error: '/run/media/guaiyihu/android_out/twrp/target/product/clover/system/lib64/libservices.so', needed by '/run/media/guaiyihu/android_out/twrp/target/product/clover/obj_arm/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin', missing and no known rule to make it

**Comment by MartinX3** [comment]
@GuaiYiHu 
did you
`repo init`
or redownload the manifest repo first?

In the "twrp-extras.xml" of the manifest is the line
`<linkfile src="libs/services" dest="frameworks/base/libs/services"`
Which should fixes it (I fixed this error by adding the services) according to

```
name: "libservices",
    srcs: [
        ":IDropBoxManagerService.aidl",
        "src/os/DropBoxManager.cpp",
        "src/os/StatsDimensionsValue.cpp",
        "src/os/StatsLogEventWrapper.cpp",
    ],
```
in the file
frameworks/base/libs/services/Android.bp

**Comment by CaptainThrowback** [comment]
I decided to try and build this, and with a shallow clone, I'm getting the same error as noted above. I confirm that I have the libs/services folder present and synced. So I'm not sure what the issue is, or why you're not facing it @MartinX3. If I comment out that line in bootable/recovery/prebuilt/Android.mk, I get a build error about partition.cpp. So the tree overall isn't functional for me.

**Comment by MartinX3** [comment]
@captainthrowback
@GuaiYiHu
I would need a device tree you faced the issue with to reproduce and fix this bug. :)

And I will try it with a shallow clone instead of a normal clone.

Because my compiled TWRP worked. :)

**Comment by CaptainThrowback** [comment]
> @CaptainThrowback
> @GuaiYiHu
> I would need a device tree you faced the issue with to reproduce and fix this bug. :)
> 
> And I will try it with a shallow clone instead of a normal clone.
> 
> Because my compiled TWRP worked. :)
@MartinX3 Take your pick:
https://github.com/CaptainThrowback/android_device_htc_ime
https://github.com/CaptainThrowback/android_device_htc_ocn

Use android-8.1 branch for either tree.

**Comment by MartinX3** [comment]
https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/issues/30
Better we use the issue ticket, instead of commenting the pull request. :)

**Pull request merged**
